# Generated by Django 6.1.1 on 2026-09-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_seed_travel_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
